create table acceptance
(
    acceptance_id   integer generated by default as identity
        primary key,
    acceptance_date timestamp not null,
    comment         varchar,
    total           real      not null
);