create table category
(
    category_id   integer generated always as identity
        primary key,
    category_name varchar(100) not null
        unique
);
insert into category(category_name) values ('Drinks');

create table items
(
    item_id           integer generated by default as identity
        primary key,
    name              varchar not null
        unique,
    price             integer not null
        constraint items_price_check
            check (price > 0),
    cost_price        real    not null
        constraint items_cost_price_check
            check (cost_price > (0)::double precision),
    quantity_in_stock real    not null,
    category_id       integer
        references category,
    surcharge_ratio   real    not null
);
insert into items(name, price, cost_price, quantity_in_stock, category_id, surcharge_ratio) VALUES ('Water',100,50.0,10.0,1,2.0);
insert into items(name, price, cost_price, quantity_in_stock, category_id, surcharge_ratio) VALUES ('Juice',100,50.0,10.0,1,2.0);

create table items_in_fridge
(
    item_in_fridge_id integer generated by default as identity
        primary key,
    item_id           integer
        references items,
    place_time        timestamp             not null,
    is_sold           boolean               not null,
    sold_date         timestamp,
    storage_time      bigint,
    expired           boolean default false not null
);