create table category
(
    category_id   integer generated always as identity
        primary key,
    category_name varchar(100) not null
        unique
);

create table items
(
    item_id           integer generated by default as identity
        primary key,
    name              varchar not null
        unique,
    price             integer not null
        constraint items_price_check
            check (price > 0),
    cost_price        real    not null
        constraint items_cost_price_check
            check (cost_price > (0)::double precision),
    quantity_in_stock real    not null,
    category_id       integer
        references category,
    surcharge_ratio   real    not null
);