create table category
(
    category_id   integer generated always as identity
        primary key,
    category_name varchar(100) not null
        unique
);

create table write_off
(
    write_off_id   integer generated by default as identity
        constraint write_off_form_pkey
            primary key,
    write_off_date timestamp not null,
    reason         varchar   not null,
    acceptance_id  integer   not null
        references acceptance,
    total          real      not null
);

create table items
(
    item_id           integer generated by default as identity
        primary key,
    name              varchar not null
        unique,
    price             integer not null
        constraint items_price_check
            check (price > 0),
    cost_price        real    not null
        constraint items_cost_price_check
            check (cost_price > (0)::double precision),
    quantity_in_stock real    not null,
    category_id       integer
        references category,
    surcharge_ratio   real    not null
);

create table ingredients
(
    ingredient_id     integer generated always as identity
        primary key,
    name              varchar(100) not null
        unique,
    cost_per_one_kilo real         not null
        constraint ingredients_cost_per_1gram_check
            check (cost_per_one_kilo > (0)::double precision),
    quantity_in_stock real         not null
);

create table ingredients_in_write_off
(
    ingredients_in_write_off_id integer generated by default as identity
        primary key,
    write_off_id                integer
        references write_off,
    ingredient_id               integer
        references ingredients,
    quantity                    real not null
        constraint ingredients_in_write_off_quantity_check
            check (quantity > (0)::double precision)
);

create table items_in_write_off
(
    items_in_write_off_id integer generated by default as identity
        primary key,
    write_off_id          integer not null
        references write_off,
    item_id               integer not null
        references items,
    quantity              real    not null
        constraint items_in_write_off_quantity_check
            check (quantity > (0)::double precision)
);