global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'customer-service:9000' ]
  - job_name: 'employees-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'employees-service:9020' ]
  - job_name: 'financial-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'financial-service:9010' ]
  - job_name: 'selling-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'selling-service:8090' ]
  - job_name: 'storage-service"'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'storage-service":8080' ]