deploymentName: financial-deployment
serviceName: financial
appLabel: financial
appName: financial
dbName: financial_db
dbHost: financialdb

replicaCount: 1

image:
  repository: biofinity/financial:V1.0
  pullPolicy: Always

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
rabbit_enabled: true
redis_enabled: false
db_enabled: true
kafka_enabled: true