create table bonuses
(
    bonus_id integer generated by default as identity
        primary key,
    edge     integer not null
        constraint unique_edge
            unique
        constraint bonuses_edge_check
            check (edge >= 0),
    value    integer not null
        constraint bonuses_value_check
            check (value >= 0)
);