create table positions
(
    position_id integer generated by default as identity
        primary key,
    name        varchar not null
        unique,
    salary      real    not null
        constraint positions_salary_check
            check (salary > (0)::double precision),
    royalty     real    not null
        constraint positions_royalty_check
            check (royalty > (0)::double precision)
);
insert into positions(name, salary, royalty) VALUES ('CEO',3000,0.1);
create table employees
(
    employee_id   integer generated by default as identity
        primary key,
    employee_name varchar not null
        unique,
    position_id   integer default 1
        references positions
);