create table positions
(
    position_id integer generated by default as identity
        primary key,
    name        varchar not null
        unique,
    salary      real    not null
        constraint positions_salary_check
            check (salary > (0)::double precision),
    royalty     real    not null
        constraint positions_royalty_check
            check (royalty > (0)::double precision)
);