
create table loyalty_levels
(
    level_id            integer generated by default as identity
        primary key,
    name                varchar not null
        constraint unique_name_constraint
            unique,
    edge                integer not null,
    discount_percentage real    not null
        constraint discount_percentage_check
            check (discount_percentage >= (0)::double precision)
    );


alter table loyalty_levels
    owner to postgres;

create table customers
(
    customer_id     integer generated by default as identity
        primary key,
    name            varchar(30) not null,
    second_name     varchar(50) not null,
    mobile_number   varchar(12) not null
        constraint unique_mobile_number_constraint
            unique,
    email           varchar
        constraint unique_email_constraint
            unique,
    total_purchases integer default 0,
    loyalty_level   integer default 1
        references loyalty_levels
);

alter table customers
    owner to postgres;

