
create table positions
(
    position_id integer generated by default as identity
        primary key,
    name        varchar not null
        unique,
    salary      real    not null
        constraint positions_salary_check
            check (salary > (0)::double precision),
    royalty     real    not null
        constraint positions_royalty_check
            check (royalty > (0)::double precision)
);

alter table positions
    owner to postgres;

create table employees
(
    employee_id   integer generated by default as identity
        primary key,
    employee_name varchar not null
        unique,
    position_id   integer
        references positions
);

alter table employees
    owner to postgres;

insert into positions values (1,'CEO',3000,0.05);


create table bonuses
(
    bonus_id integer generated by default as identity
        primary key,
    edge     integer not null
        constraint unique_edge
            unique
        constraint bonuses_edge_check
            check (edge >= 0),
    value    integer not null
        constraint bonuses_value_check
            check (value >= 0)
);

alter table bonuses
    owner to postgres;

create table salary
(
    salary_id                integer generated by default as identity
        primary key,
    date                     timestamp             not null,
    salary                   real                  not null
        constraint salary_salary_check
            check (salary > (0)::double precision),
    royalty                  real,
    revenue                  integer default 0
        constraint salary_revenue_check
            check (revenue >= 0),
    total                    real                  not null
        constraint salary_total_check
            check (total > (0)::double precision),
    salary_session_is_closed boolean default false not null,
    employee_id              integer
        references employees,
    bonus_value              integer
        constraint salary_bonus_value_check
            check (bonus_value >= 0)
);

alter table salary
    owner to postgres;

insert into bonuses values (1,0,0);