
create sequence daily_financial_report_daily_financial_report_id_seq;

alter sequence daily_financial_report_daily_financial_report_id_seq owner to postgres;

create table total_financial_flow
(
    total_cash_flow_id integer generated by default as identity
        primary key,
    cash_amount        integer not null
        constraint total_financial_flow_cash_amount_check
            check ((cash_amount)::numeric >= (0)::numeric),
    card_amount        integer not null
        constraint total_financial_flow_card_amount_check
            check ((card_amount)::numeric >= (0)::numeric)
);

insert into total_financial_flow values (1,0,0);

alter table total_financial_flow
    owner to postgres;

create table sessions
(
    session_id           integer generated by default as identity
        constraint daily_financial_report_pkey
            primary key,
    opening_session_date timestamp                                  not null,
    initial_cash         integer                                    not null
        constraint daily_financial_report_initial_cash_check
            check (initial_cash >= 0),
    cash_inflow          integer                                    not null
        constraint daily_financial_report_cash_inflow_check
            check (cash_inflow >= 0),
    cash_expense         integer                                    not null
        constraint daily_financial_report_cash_expense_check
            check (cash_expense >= 0),
    card_payment         integer                                    not null
        constraint daily_financial_report_card_inflow_check
            check (card_payment >= 0),
    order_quantity       integer                                    not null
        constraint daily_financial_report_order_quantity_check
            check (order_quantity >= 0),
    total_money          integer                                    not null
        constraint daily_financial_report_total_money_check
            check (total_money >= 0),
    finite_cash          integer                                    not null
        constraint daily_financial_report_finite_cash_check
            check (finite_cash >= 0),
    closing_session_date timestamp,
    session_is_closed    boolean                                    not null,
    cash_payment         integer                                    not null
        constraint daily_financial_report_cashpayment_check
            check (cash_payment >= 0),
    employee_name          varchar default 'admin'::character varying not null
);

insert into sessions values (0,localtimestamp,0,0,0,0,0,0,0,localtimestamp,true,0,'admin');

alter table sessions
    owner to postgres;

alter sequence daily_financial_report_daily_financial_report_id_seq owned by sessions.session_id;

create table transaction_types
(
    transaction_type_id integer generated by default as identity
        primary key,
    name                varchar not null
        unique
);

alter table transaction_types
    owner to postgres;

create table transactions
(
    transaction_id integer generated by default as identity
        primary key,
    date           timestamp not null,
    type           integer   not null
        references transaction_types,
    sum            integer   not null
        constraint transactions_sum_check
            check (sum >= 0),
    session_id     integer   not null
        constraint transactions_financial_day_id_fkey
            references sessions
);

alter table transactions
    owner to postgres;

insert into total_financial_flow values (1,0,0);
insert into transaction_types values (1,'Cash deposit');
insert into transaction_types values (2,'Cash withdrawal');
insert into transaction_types values (3,'Card payment');
insert into transaction_types values (4,'Cash payment');
