deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: biofinity/eureka-server:V1.0
  pullPolicy: Always

containerPort: 8070

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
rabbit_enabled: true
redis_enabled: false
db_enabled: false
kafka_enabled: false