
create table loyalty_levels
(
    level_id            integer generated by default as identity
        primary key,
    name                varchar not null
        constraint unique_name_constraint
            unique,
    edge                integer not null,
    discount_percentage real    not null
        constraint discount_percentage_check
            check (discount_percentage >= (0)::double precision)
    );



