deploymentName: storage-deployment
serviceName: storage
appLabel: storage
appName: storage
dbName: storage_db
dbHost: storagedb

replicaCount: 1

image:
  repository: biofinity/storage-service:V1.0

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
rabbit_enabled: true
redis_enabled: false
db_enabled: true
kafka_enabled: false