create table payment_methods
(
    method_id   integer generated by default as identity
        primary key,
    method_name varchar not null
);
insert into payment_methods(method_id,method_name) values (1,'card');

create table orders
(
    order_id                       integer generated by default as identity
        primary key,
    order_date                     timestamp         not null,
    total                          integer           not null
        constraint orders_total_check
            check (total > 0)
        constraint orders_total_check1
            check (total > 0),
    discount                       integer           not null,
    total_with_dsc                 real              not null,
    payment_id                     integer           not null
        references payment_methods,
    customer_id                    integer,
    customer_purchase_confirmation boolean,
    session_id                     integer default 0 not null,
    employee_name                  varchar default 0 not null
);