create table sessions
(
    session_id           integer generated by default as identity
        constraint daily_financial_report_pkey
            primary key,
    opening_session_date timestamp                                  not null,
    initial_cash         integer                                    not null
        constraint daily_financial_report_initial_cash_check
            check (initial_cash >= 0),
    cash_inflow          integer                                    not null
        constraint daily_financial_report_cash_inflow_check
            check (cash_inflow >= 0),
    cash_expense         integer                                    not null
        constraint daily_financial_report_cash_expense_check
            check (cash_expense >= 0),
    card_payment         integer                                    not null
        constraint daily_financial_report_card_inflow_check
            check (card_payment >= 0),
    order_quantity       integer                                    not null
        constraint daily_financial_report_order_quantity_check
            check (order_quantity >= 0),
    total_money          integer                                    not null
        constraint daily_financial_report_total_money_check
            check (total_money >= 0),
    finite_cash          integer                                    not null
        constraint daily_financial_report_finite_cash_check
            check (finite_cash >= 0),
    closing_session_date timestamp,
    session_is_closed    boolean                                    not null,
    cash_payment         integer                                    not null
        constraint daily_financial_report_cashpayment_check
            check (cash_payment >= 0),
    employee_name          varchar default 'admin'::character varying not null
);
