create table total_financial_flow
(
    total_cash_flow_id integer generated by default as identity
        primary key,
    cash_amount        integer not null
        constraint total_financial_flow_cash_amount_check
            check ((cash_amount)::numeric >= (0)::numeric),
    card_amount        integer not null
        constraint total_financial_flow_card_amount_check
            check ((card_amount)::numeric >= (0)::numeric)
);
insert into total_financial_flow (cash_amount,card_amount) values (0,0);
create table transaction_types
(
    transaction_type_id integer generated by default as identity
        primary key,
    name                varchar not null
        unique
);
insert into transaction_types(name) values ('Cash');
create table transactions
(
    transaction_id integer generated by default as identity
        primary key,
    date           timestamp not null,
    type           integer   not null
        references transaction_types,
    sum            integer   not null
        constraint transactions_sum_check
            check (sum >= 0),
    session_id     integer   not null
        constraint transactions_financial_day_id_fkey
            references sessions
);
